# Generated by Django 4.0.1 on 2022-02-22 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipping_addresses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='shippingaddress',
            old_name='users',
            new_name='user',
        ),
    ]
